apiVersion: v1
kind: Service
metadata:
  name: spring-rest-api
  labels:
    name: spring-rest-api
spec:
  ports:
    - nodePort: 30162
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-rest-api
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-rest-api
spec:
  selector:
    matchLabels:
      app: spring-rest-api
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-rest-api
    spec:
      containers:
        - name: spring-rest-api
          image: gaava/tech-challenge-fiap-images:stable
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password