apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-conf
data:
  host: postgres
  name: galega_burguer

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
data:
  postgres_user: cG9zdGdyZXM=
  postgres_password: cG9zdGdyZXM=